version: '3'

volumes:
  bundle:
  elastic:

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      # - sidekiq
      - elasticsearch
    tmpfs: /app/tmp
    ports:
      - "3000:3000"
    env_file: docker-env
    tty: true
    stdin_open: true

  # sidekiq:
  #   <<: rails
  #   depends_on:
  #     - redis
  #     - db
  #     - elasticsearch
  #   command: bundle exec sidekiq
  #   ports:

  # redis:
  #   container_name: redis
  #   image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    env_file: docker-env
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
