FROM ruby:2.6

LABEL maintainer="Sokly <sokly@instedd.org>"

RUN apt-get update -qq && \
  apt-get install -y nodejs postgresql-client && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app
WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY . /app
